[package]
name = "ffi-test"
version = "0.1.0"
authors = ["AdaShoelace <pierre.leidbring@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ffi_test"
crate-type = ["cdylib"] #dynamic library

[dependencies]
